package main

const ERROR_NO_ERROR = 0
const ERROR_ACTION_NOT_DEFINED = 1
const ERROR_ACTION_NOT_EXIST = 2
const ERROR_FILE_NOT_DEFINED = 3
const ERROR_FILE_NOT_EXIST = 4
const ERROR_FILE_READ_PERMISSION = 5
const ERROR_UNKNOWN = 6
